In [22]:
import pandas as pd
import numpy as np

df = pd.read_csv("Stock Prices Dataset raw.csv")

df.head()

#I converted the date column into datetime format for time-series analysis.”
df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')

In [23]:
# Basic data understanding and validation.

df.info()
df.describe()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 497472 entries, 0 to 497471
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   symbol         497472 non-null  object
 1   date           497472 non-null  datetime64[ns]
 2   open price     497461 non-null  float64
 3   high price     497464 non-null  float64
 4   low price      497464 non-null  float64
 5   close price    497472 non-null  float64
 6   volume traded  497472 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 26.6+ MB

np.int64(0)

In [24]:
df = df.sort_values(["symbol", "date"])
df[["open price", "high price", "low price"]] = (
    df.groupby("symbol")[["open price", "high price", "low price"]]
      .ffill()
      .bfill()
)

(df["low price"] > df["high price"]).sum()

np.int64(1)

In [25]:
#Removing rows where low price was greater than high price.
df = df[df["low price"] <= df["high price"]]

#Keep only those rows where the low price is less than or equal to the high price. Remove everything else.

#Re-checked the dataset after cleaning.
(df["low price"] > df["high price"]).sum()

np.int64(0)

In [26]:
# Display rows containing any remaining missing values (data validation check)

df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [symbol, date, open price, high price, low price, close price, volume traded]
Index: []

In [32]:
# Checking for duplicate records based on symbol and date

df.duplicated(subset=["symbol", "date"]).sum()

np.int64(0)

In [33]:
# Final data validation before saving cleaned dataset
print("Missing values:\n", df.isnull().sum())
print("\nDuplicate records (symbol + date):", 
      df.duplicated(subset=["symbol", "date"]).sum())

df.head()

Missing values:
 symbol           0
date             0
open price       0
high price       0
low price        0
close price      0
volume traded    0
dtype: int64

Duplicate records (symbol + date): 0

,symbol,date,open price,high price,low price,close price,volume traded
0,A,2014-01-02,57.10,57.100,56.15,56.21,1916160
1,A,2014-01-03,56.39,57.345,56.26,56.92,1866651
2,A,2014-01-06,57.40,57.700,56.56,56.64,1777472
3,A,2014-01-07,56.95,57.630,56.93,57.45,1463208
4,A,2014-01-08,57.33,58.540,57.17,58.39,2659468

In [ ]:
# Save dataset after data cleaning
df.to_csv("complete_stock_dataset_cleaned.csv", index=False)