In [7]:
import pandas as pd
import numpy as np

# Load cleaned dataset
df = pd.read_csv("complete_stock_dataset_cleaned.csv")

# Ensure proper time order for time-series calculations
df = df.sort_values(["symbol", "date"])

# Feature engineering: daily return – percentage change in closing price
df["daily_return"] = df.groupby("symbol")["close price"].pct_change()

# Preview
df.head()

,symbol,date,open price,high price,low price,close price,volume traded,daily_return,price_range,ma10,volatility_10
255596,A,01-02-2016,37.37,37.945,37.000,37.69,2666567,NaN,0.945,37.329,0.018565
381496,A,01-02-2017,48.93,49.810,48.680,49.26,2244604,0.306978,1.130,48.113,0.014706
265516,A,01-03-2016,37.63,38.660,37.610,38.59,2760200,-0.216606,1.050,37.634,0.017128
390996,A,01-03-2017,51.62,52.260,51.620,52.04,2026600,0.348536,0.640,51.499,0.011924
29523,A,01-04-2014,56.20,56.620,55.835,56.36,2090720,0.083013,0.785,55.667,0.010466

In [8]:
# Feature engineering: daily return – percentage change in closing price
df["daily_return"] = df.groupby("symbol")["close price"].pct_change()

# Feature engineering: price range
df["price_range"] = df["high price"] - df["low price"]

In [9]:
# Feature engineering: 10-day moving average
df["ma10"] = (
    df.groupby("symbol")["close price"]
      .transform(lambda x: x.rolling(10).mean())
)

# Feature engineering: 10-day rolling volatility
df["volatility_10"] = (
    df.groupby("symbol")["daily_return"]
      .transform(lambda x: x.rolling(10).std())
)

In [10]:
# Removing rows with NaNs created by rolling features
df = df.dropna(subset=["daily_return", "ma10", "volatility_10"])

In [11]:
df.head()

,symbol,date,open price,high price,low price,close price,volume traded,daily_return,price_range,ma10,volatility_10
172302,A,01-06-2015,41.43,41.430,40.85,40.92,2440065,-0.266667,0.580,47.097,0.275536
297297,A,01-06-2016,45.75,46.095,45.45,45.95,1734386,0.122923,0.645,46.766,0.261642
423037,A,01-06-2017,60.01,60.770,59.81,60.73,2100441,0.321654,0.960,48.980,0.262176
60071,A,01-07-2014,57.74,58.440,57.38,58.25,2010785,-0.040836,1.060,49.601,0.245786
183065,A,01-07-2015,38.89,39.295,38.75,39.26,4486572,-0.326009,0.545,47.891,0.270302

In [12]:
# Save dataset for analysis
df.to_csv("stock_data_feature_engineered.csv", index=False)